<?php

namespace Database\Seeders;

use App\Models\Clinic;
use App\Models\Doctor;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\File;

class DoctorSeeder extends Seeder
{
    public function run(): void
    {
        $doctors = [
            // Clinic 1 - Human Doctors
            [
                'name' => 'Dr. Ahmed Hassan',
                'email' => 'ahmed.hassan@example.com',
                'password' => Hash::make('password123'),
                'specialization' => 'General Physician',
                'bio' => 'Experienced in general health and internal medicine.',
                'clinic_address' => '123 Main St, City A',
                'role' => 'human',
                'clinic_type' => 'clinic',
                'address' => 'City A',
                'phone' => '01234567890',
                'image' => 'doctor1.jpg',
                'clinic_id' => 1,
            ],
            [
                'name' => 'Dr. Mohamed Ali',
                'email' => 'mohamed.ali.clinic1@example.com',
                'password' => Hash::make('password123'),
                'specialization' => 'Cardiologist',
                'bio' => 'Expert in heart conditions and treatments.',
                'clinic_address' => '123 Main St, City A',
                'role' => 'human',
                'clinic_type' => 'clinic',
                'address' => 'City A',
                'phone' => '01234567891',
                'image' => 'default.jpg',
                'clinic_id' => 1,
            ],
            [
                'name' => 'Dr. Fatma Mahmoud',
                'email' => 'fatma.mahmoud.clinic1@example.com',
                'password' => Hash::make('password123'),
                'specialization' => 'Neurologist',
                'bio' => 'Specialist in brain and nervous system disorders.',
                'clinic_address' => '123 Main St, City A',
                'role' => 'human',
                'clinic_type' => 'clinic',
                'address' => 'City A',
                'phone' => '01234567892',
                'image' => 'default1.jpg',
                'clinic_id' => 1,
            ],
            [
                'name' => 'Dr. Omar Ibrahim',
                'email' => 'omar.ibrahim.clinic1@example.com',
                'password' => Hash::make('password123'),
                'specialization' => 'Orthopedic Surgeon',
                'bio' => 'Expert in bone and joint surgeries.',
                'clinic_address' => '123 Main St, City A',
                'role' => 'human',
                'clinic_type' => 'clinic',
                'address' => 'City A',
                'phone' => '01234567893',
                'image' => 'default.jpg',
                'clinic_id' => 1,
            ],
            [
                'name' => 'Dr. Nada Samir',
                'email' => 'nada.samir.clinic1@example.com',
                'password' => Hash::make('password123'),
                'specialization' => 'Gynecologist',
                'bio' => 'Specialist in women\'s health and reproductive system.',
                'clinic_address' => '123 Main St, City A',
                'role' => 'human',
                'clinic_type' => 'clinic',
                'address' => 'City A',
                'phone' => '01234567894',
                'image' => 'default1.jpg',
                'clinic_id' => 1,
            ],
            // Clinic 2 - Human Doctors
            [
                'name' => 'Dr. Sarah Youssef',
                'email' => 'sara.youssef@example.com',
                'password' => Hash::make('password123'),
                'specialization' => 'Dentist',
                'bio' => 'Expert in dental surgery and cosmetic dentistry.',
                'clinic_address' => '456 Smile Ave, City B',
                'role' => 'human',
                'clinic_type' => 'clinic',
                'address' => 'City B',
                'phone' => '01234567891',
                'image' => 'doctor2.jpg',
                'clinic_id' => 2,
            ],
            [
                'name' => 'Dr. Tarek Mohamed',
                'email' => 'tarek.mohamed.clinic2@example.com',
                'password' => Hash::make('password123'),
                'specialization' => 'Endodontist',
                'bio' => 'Specialist in root canal treatments.',
                'clinic_address' => '456 Smile Ave, City B',
                'role' => 'human',
                'clinic_type' => 'clinic',
                'address' => 'City B',
                'phone' => '01234567896',
                'image' => 'default.jpg',
                'clinic_id' => 2,
            ],
            [
                'name' => 'Dr. Hala Kamal',
                'email' => 'hala.kamal.clinic2@example.com',
                'password' => Hash::make('password123'),
                'specialization' => 'Periodontist',
                'bio' => 'Expert in gum diseases and treatments.',
                'clinic_address' => '456 Smile Ave, City B',
                'role' => 'human',
                'clinic_type' => 'clinic',
                'address' => 'City B',
                'phone' => '01234567897',
                'image' => 'default1.jpg',
                'clinic_id' => 2,
            ],
            [
                'name' => 'Dr. Wael Hassan',
                'email' => 'wael.hassan.clinic2@example.com',
                'password' => Hash::make('password123'),
                'specialization' => 'Orthodontist',
                'bio' => 'Specialist in teeth alignment and braces.',
                'clinic_address' => '456 Smile Ave, City B',
                'role' => 'human',
                'clinic_type' => 'clinic',
                'address' => 'City B',
                'phone' => '01234567898',
                'image' => 'default.jpg',
                'clinic_id' => 2,
            ],
            [
                'name' => 'Dr. Mona Adel',
                'email' => 'mona.adel.clinic2@example.com',
                'password' => Hash::make('password123'),
                'specialization' => 'Pediatric Dentist',
                'bio' => 'Specialist in children\'s dental care.',
                'clinic_address' => '456 Smile Ave, City B',
                'role' => 'human',
                'clinic_type' => 'clinic',
                'address' => 'City B',
                'phone' => '01234567899',
                'image' => 'default1.jpg',
                'clinic_id' => 2,
            ],
            // Clinic 3 - Human Doctors
            [
                'name' => 'Dr. Mostafa Nabil',
                'email' => 'mostafa.nabil@example.com',
                'password' => Hash::make('password123'),
                'specialization' => 'Ophthalmologist',
                'bio' => 'Providing advanced eye care and surgery.',
                'clinic_address' => '789 Vision Rd, City C',
                'role' => 'human',
                'clinic_type' => 'clinic',
                'address' => 'City C',
                'phone' => '01234567892',
                'image' => 'doctor3.jpg',
                'clinic_id' => 3,
            ],
            [
                'name' => 'Dr. Rania Samy',
                'email' => 'rania.samy.clinic3@example.com',
                'password' => Hash::make('password123'),
                'specialization' => 'Retina Specialist',
                'bio' => 'Expert in retinal diseases and treatments.',
                'clinic_address' => '789 Vision Rd, City C',
                'role' => 'human',
                'clinic_type' => 'clinic',
                'address' => 'City C',
                'phone' => '01234567901',
                'image' => 'default1.jpg',
                'clinic_id' => 3,
            ],
            [
                'name' => 'Dr. Khaled Farouk',
                'email' => 'khaled.farouk.clinic3@example.com',
                'password' => Hash::make('password123'),
                'specialization' => 'Cornea Specialist',
                'bio' => 'Specialist in cornea transplants and diseases.',
                'clinic_address' => '789 Vision Rd, City C',
                'role' => 'human',
                'clinic_type' => 'clinic',
                'address' => 'City C',
                'phone' => '01234567902',
                'image' => 'default.jpg',
                'clinic_id' => 3,
            ],
            [
                'name' => 'Dr. Dina Magdy',
                'email' => 'dina.magdy.clinic3@example.com',
                'password' => Hash::make('password123'),
                'specialization' => 'Pediatric Ophthalmologist',
                'bio' => 'Specialist in children\'s eye care.',
                'clinic_address' => '789 Vision Rd, City C',
                'role' => 'human',
                'clinic_type' => 'clinic',
                'address' => 'City C',
                'phone' => '01234567903',
                'image' => 'default1.jpg',
                'clinic_id' => 3,
            ],
            [
                'name' => 'Dr. Sherif Ahmed',
                'email' => 'sherif.ahmed.clinic3@example.com',
                'password' => Hash::make('password123'),
                'specialization' => 'Glaucoma Specialist',
                'bio' => 'Expert in glaucoma diagnosis and treatment.',
                'clinic_address' => '789 Vision Rd, City C',
                'role' => 'human',
                'clinic_type' => 'clinic',
                'address' => 'City C',
                'phone' => '01234567904',
                'image' => 'default.jpg',
                'clinic_id' => 3,
            ],
            // Clinic 4 - Human Doctors
            [
                'name' => 'Dr. Mariam Khaled',
                'email' => 'mariam.khaled@example.com',
                'password' => Hash::make('password123'),
                'specialization' => 'Pediatrician',
                'bio' => 'Specialist in child healthcare.',
                'clinic_address' => '101 Kids Lane, City D',
                'role' => 'human',
                'clinic_type' => 'clinic',
                'address' => 'City D',
                'phone' => '01234567893',
                'image' => 'doctor4.jpg',
                'clinic_id' => 4,
            ],
            [
                'name' => 'Dr. Ahmed Samir',
                'email' => 'ahmed.samir.clinic4@example.com',
                'password' => Hash::make('password123'),
                'specialization' => 'Neonatologist',
                'bio' => 'Specialist in newborn care.',
                'clinic_address' => '101 Kids Lane, City D',
                'role' => 'human',
                'clinic_type' => 'clinic',
                'address' => 'City D',
                'phone' => '01234567906',
                'image' => 'default.jpg',
                'clinic_id' => 4,
            ],
            [
                'name' => 'Dr. Yasmine Adel',
                'email' => 'yasmine.adel.clinic4@example.com',
                'password' => Hash::make('password123'),
                'specialization' => 'Pediatric Cardiologist',
                'bio' => 'Expert in children\'s heart conditions.',
                'clinic_address' => '101 Kids Lane, City D',
                'role' => 'human',
                'clinic_type' => 'clinic',
                'address' => 'City D',
                'phone' => '01234567907',
                'image' => 'default1.jpg',
                'clinic_id' => 4,
            ],
            [
                'name' => 'Dr. Karim Mohamed',
                'email' => 'karim.mohamed.clinic4@example.com',
                'password' => Hash::make('password123'),
                'specialization' => 'Pediatric Neurologist',
                'bio' => 'Specialist in children\'s neurological disorders.',
                'clinic_address' => '101 Kids Lane, City D',
                'role' => 'human',
                'clinic_type' => 'clinic',
                'address' => 'City D',
                'phone' => '01234567908',
                'image' => 'default.jpg',
                'clinic_id' => 4,
            ],
            [
                'name' => 'Dr. Nourhan Ali',
                'email' => 'nourhan.ali.clinic4@example.com',
                'password' => Hash::make('password123'),
                'specialization' => 'Pediatric Endocrinologist',
                'bio' => 'Expert in children\'s hormonal disorders.',
                'clinic_address' => '101 Kids Lane, City D',
                'role' => 'human',
                'clinic_type' => 'clinic',
                'address' => 'City D',
                'phone' => '01234567909',
                'image' => 'default1.jpg',
                'clinic_id' => 4,
            ],
            // Clinic 5 - Human Doctors
            [
                'name' => 'Dr. Amr Adel',
                'email' => 'amr.adel@example.com',
                'password' => Hash::make('password123'),
                'specialization' => 'Dermatologist',
                'bio' => 'Skin care and cosmetic treatment expert.',
                'clinic_address' => '202 Skin Blvd, City E',
                'role' => 'human',
                'clinic_type' => 'clinic',
                'address' => 'City E',
                'phone' => '01234567894',
                'image' => 'doctor5.jpg',
                'clinic_id' => 5,
            ],
            [
                'name' => 'Dr. Laila Hassan',
                'email' => 'laila.hassan.clinic5@example.com',
                'password' => Hash::make('password123'),
                'specialization' => 'Cosmetic Dermatologist',
                'bio' => 'Expert in cosmetic skin treatments.',
                'clinic_address' => '202 Skin Blvd, City E',
                'role' => 'human',
                'clinic_type' => 'clinic',
                'address' => 'City E',
                'phone' => '01234567911',
                'image' => 'default1.jpg',
                'clinic_id' => 5,
            ],
            [
                'name' => 'Dr. Omar Samy',
                'email' => 'omar.samy.clinic5@example.com',
                'password' => Hash::make('password123'),
                'specialization' => 'Dermatopathologist',
                'bio' => 'Specialist in skin disease diagnosis.',
                'clinic_address' => '202 Skin Blvd, City E',
                'role' => 'human',
                'clinic_type' => 'clinic',
                'address' => 'City E',
                'phone' => '01234567912',
                'image' => 'default.jpg',
                'clinic_id' => 5,
            ],
            [
                'name' => 'Dr. Nadine Kamal',
                'email' => 'nadine.kamal.clinic5@example.com',
                'password' => Hash::make('password123'),
                'specialization' => 'Pediatric Dermatologist',
                'bio' => 'Specialist in children\'s skin conditions.',
                'clinic_address' => '202 Skin Blvd, City E',
                'role' => 'human',
                'clinic_type' => 'clinic',
                'address' => 'City E',
                'phone' => '01234567913',
                'image' => 'default1.jpg',
                'clinic_id' => 5,
            ],
            [
                'name' => 'Dr. Tamer Mohamed',
                'email' => 'tamer.mohamed.clinic5@example.com',
                'password' => Hash::make('password123'),
                'specialization' => 'Mohs Surgeon',
                'bio' => 'Expert in skin cancer surgery.',
                'clinic_address' => '202 Skin Blvd, City E',
                'role' => 'human',
                'clinic_type' => 'clinic',
                'address' => 'City E',
                'phone' => '01234567914',
                'image' => 'default.jpg',
                'clinic_id' => 5,
            ],
            // Veterinary Doctors - Clinic 1
            [
                'name' => 'Dr. Lina Gamal',
                'email' => 'lina.gamal@example.com',
                'password' => Hash::make('password123'),
                'specialization' => 'Nutritionist',
                'bio' => 'Helps patients achieve optimal health through diet and lifestyle.',
                'clinic_address' => '12 Wellness St, City X',
                'role' => 'vet',
                'clinic_type' => 'vet',
                'address' => 'City X',
                'phone' => '01122334455',
                'image' => 'doctor6.jpg',
                'vet_id' => 1,
            ],
            [
                'name' => 'Dr. Nouran Adel',
                'email' => 'nouran.adel.vet1@example.com',
                'password' => Hash::make('password123'),
                'specialization' => 'Avian Medicine',
                'bio' => 'Specialist in bird health and treatment.',
                'clinic_address' => '12 Wellness St, City X',
                'role' => 'vet',
                'clinic_type' => 'vet',
                'address' => 'City X',
                'phone' => '01122334456',
                'image' => 'default1.jpg',
                'vet_id' => 1,
            ],
            [
                'name' => 'Dr. Ahmed Samy',
                'email' => 'ahmed.samy.vet1@example.com',
                'password' => Hash::make('password123'),
                'specialization' => 'Exotic Animal Medicine',
                'bio' => 'Expert in treating reptiles and exotic pets.',
                'clinic_address' => '12 Wellness St, City X',
                'role' => 'vet',
                'clinic_type' => 'vet',
                'address' => 'City X',
                'phone' => '01122334457',
                'image' => 'default.jpg',
                'vet_id' => 1,
            ],
            [
                'name' => 'Dr. Mona Hassan',
                'email' => 'mona.hassan.vet1@example.com',
                'password' => Hash::make('password123'),
                'specialization' => 'Veterinary Surgery',
                'bio' => 'Specialist in surgical procedures for animals.',
                'clinic_address' => '12 Wellness St, City X',
                'role' => 'vet',
                'clinic_type' => 'vet',
                'address' => 'City X',
                'phone' => '01122334458',
                'image' => 'default1.jpg',
                'vet_id' => 1,
            ],
            [
                'name' => 'Dr. Tarek Mohamed',
                'email' => 'tarek.mohamed.vet1@example.com',
                'password' => Hash::make('password123'),
                'specialization' => 'Veterinary Dermatology',
                'bio' => 'Expert in animal skin conditions and treatments.',
                'clinic_address' => '12 Wellness St, City X',
                'role' => 'vet',
                'clinic_type' => 'vet',
                'address' => 'City X',
                'phone' => '01122334459',
                'image' => 'default.jpg',
                'vet_id' => 1,
            ],
            // Veterinary Doctors - Clinic 2
            [
                'name' => 'Dr. Karim Elsaid',
                'email' => 'karim.elsaid@example.com',
                'password' => Hash::make('password123'),
                'specialization' => 'Veterinary Medicine',
                'bio' => 'Certified veterinarian focused on animal health.',
                'clinic_address' => '78 Vet Zone, City Y',
                'role' => 'vet',
                'clinic_type' => 'vet',
                'address' => 'City Y',
                'phone' => '01099887766',
                'image' => 'doctor7.jpg',
                'vet_id' => 2,
            ],
            [
                'name' => 'Dr. Hossam Badr',
                'email' => 'hossam.badr.vet2@example.com',
                'password' => Hash::make('password123'),
                'specialization' => 'Equine Medicine',
                'bio' => 'Expert in horse health and treatment.',
                'clinic_address' => '78 Vet Zone, City Y',
                'role' => 'vet',
                'clinic_type' => 'vet',
                'address' => 'City Y',
                'phone' => '01099887767',
                'image' => 'default.jpg',
                'vet_id' => 2,
            ],
            [
                'name' => 'Dr. Yasmine Nader',
                'email' => 'yasmine.nader.vet2@example.com',
                'password' => Hash::make('password123'),
                'specialization' => 'Veterinary Internal Medicine',
                'bio' => 'Specialist in animal internal diseases.',
                'clinic_address' => '78 Vet Zone, City Y',
                'role' => 'vet',
                'clinic_type' => 'vet',
                'address' => 'City Y',
                'phone' => '01099887768',
                'image' => 'default1.jpg',
                'vet_id' => 2,
            ],
            [
                'name' => 'Dr. Omar Adel',
                'email' => 'omar.adel.vet2@example.com',
                'password' => Hash::make('password123'),
                'specialization' => 'Veterinary Cardiology',
                'bio' => 'Expert in animal heart conditions.',
                'clinic_address' => '78 Vet Zone, City Y',
                'role' => 'vet',
                'clinic_type' => 'vet',
                'address' => 'City Y',
                'phone' => '01099887769',
                'image' => 'default.jpg',
                'vet_id' => 2,
            ],
            [
                'name' => 'Dr. Nadia Kamal',
                'email' => 'nadia.kamal.vet2@example.com',
                'password' => Hash::make('password123'),
                'specialization' => 'Veterinary Oncology',
                'bio' => 'Specialist in animal cancer treatment.',
                'clinic_address' => '78 Vet Zone, City Y',
                'role' => 'vet',
                'clinic_type' => 'vet',
                'address' => 'City Y',
                'phone' => '01099887770',
                'image' => 'default1.jpg',
                'vet_id' => 2,
            ],
            // Veterinary Doctors - Clinic 3
            [
                'name' => 'Dr. Yasmin Nader',
                'email' => 'yasmin.nader@example.com',
                'password' => Hash::make('password123'),
                'specialization' => 'Veterinary Medicine',
                'bio' => 'Expert in animal health and treatment.',
                'clinic_address' => '33 Vet Center, City Z',
                'role' => 'vet',
                'clinic_type' => 'vet',
                'address' => 'City Z',
                'phone' => '01233445566',
                'image' => 'doctor8.jpg',
                'vet_id' => 3,
            ],
            [
                'name' => 'Dr. Mohamed Ali',
                'email' => 'mohamed.ali.vet3@example.com',
                'password' => Hash::make('password123'),
                'specialization' => 'Veterinary Dentistry',
                'bio' => 'Specialist in animal dental care.',
                'clinic_address' => '33 Vet Center, City Z',
                'role' => 'vet',
                'clinic_type' => 'vet',
                'address' => 'City Z',
                'phone' => '01233445567',
                'image' => 'default.jpg',
                'vet_id' => 3,
            ],
            [
                'name' => 'Dr. Sara Mahmoud',
                'email' => 'sara.mahmoud.vet3@example.com',
                'password' => Hash::make('password123'),
                'specialization' => 'Veterinary Ophthalmology',
                'bio' => 'Expert in animal eye care and treatment.',
                'clinic_address' => '33 Vet Center, City Z',
                'role' => 'vet',
                'clinic_type' => 'vet',
                'address' => 'City Z',
                'phone' => '01233445568',
                'image' => 'default1.jpg',
                'vet_id' => 3,
            ],
            [
                'name' => 'Dr. Khaled Samir',
                'email' => 'khaled.samir.vet3@example.com',
                'password' => Hash::make('password123'),
                'specialization' => 'Veterinary Neurology',
                'bio' => 'Specialist in animal nervous system disorders.',
                'clinic_address' => '33 Vet Center, City Z',
                'role' => 'vet',
                'clinic_type' => 'vet',
                'address' => 'City Z',
                'phone' => '01233445569',
                'image' => 'default.jpg',
                'vet_id' => 3,
            ],
            [
                'name' => 'Dr. Dina Farouk',
                'email' => 'dina.farouk.vet3@example.com',
                'password' => Hash::make('password123'),
                'specialization' => 'Veterinary Nutrition',
                'bio' => 'Expert in animal diet and nutrition.',
                'clinic_address' => '33 Vet Center, City Z',
                'role' => 'vet',
                'clinic_type' => 'vet',
                'address' => 'City Z',
                'phone' => '01233445570',
                'image' => 'default1.jpg',
                'vet_id' => 3,
            ],
        ];

        foreach ($doctors as $doctorData) {
            $originalPath = public_path('images/human/' . $doctorData['image']);
            $storagePath = 'doctors/' . $doctorData['image'];

            if (File::exists($originalPath)) {
                Storage::disk('public')->put($storagePath, File::get($originalPath));
            }

            Doctor::create([
                'name' => $doctorData['name'],
                'email' => $doctorData['email'],
                'password' => $doctorData['password'],
                'specialization' => $doctorData['specialization'],
                'bio' => $doctorData['bio'],
                'clinic_address' => $doctorData['clinic_address'],
                'role' => $doctorData['role'],
                'address' => $doctorData['address'],
                'phone' => $doctorData['phone'],
                'image' => $storagePath,
                'clinic_id' => $doctorData['role'] === 'human' ? $doctorData['clinic_id'] : null,
                'vet_id' => $doctorData['role'] === 'vet' ? $doctorData['vet_id'] : null,
                'clinic_type' => $doctorData['clinic_type'] === 'clinic' ? \App\Models\Clinic::class : \App\Models\Vet::class,
            ]);
        }
    }
}
