<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\Category;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Storage;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'category_id' => 1,
                'name' => 'aloe vera gel',
                'description' => '99% natural aloe vera gel for moisturizing and soothing the skin, suitable for all skin types',
                'image' => 'aloe vera gel.png',
                'price' => 35.99,
                'stock' => 15,
                'quantity' => 55,
            ],
            [
                'category_id' => 1,
                'name' => 'Vitamin C Serum',
                'description' => '20% Vitamin C serum to brighten the skin, even tone, and reduce wrinkles',
                'image' => 'Vitamin C Serum.png',
                'price' => 89.99,
                'stock' => 15,
                'quantity' => 45,
            ],
            [
                'category_id' => 1,
                'name' => 'Foaming Facial Cleanser',
                'description' => 'Gentle foaming facial cleanser that deeply cleanses without drying the skin, soap-free',
                'image' => 'Foaming Facial Cleanser.png',
                'price' => 45.50,
                'stock' => 0,
                'quantity' => 60,
            ],
            [
                'category_id' => 1,
                'name' => 'Hydrating Facial Cream',
                'description' => 'Rich moisturizing cream with hyaluronic acid to keep skin hydrated for 24 hours',
                'image' => 'Hydrating Facial Cream.png',
                'price' => 65.00,
                'stock' => 9,
                'quantity' => 30,
            ],
            [
                'category_id' => 1,
                'name' => 'Micellar Water',
                'description' => 'Micellar water for gently removing makeup and cleansing the skin without rinsing',
                'image' => 'Micellar Water.png',
                'price' => 32.99,
                'stock' => 20,
                'quantity' => 100,
            ],
            [
                'category_id' => 1,
                'name' => 'Sunscreen SPF 50+',
                'description' => 'Lightweight, non-greasy broad-spectrum sunscreen for daily UV protection',
                'image' => 'Sunscreen.png',
                'price' => 55.00,
                'stock' => 11,
                'quantity' => 20,
            ],
            [
                'category_id' => 1,
                'name' => 'Night Repair Cream',
                'description' => 'Night cream rich in antioxidants to rejuvenate skin while sleeping',
                'image' => 'Night Repair Cream.png',
                'price' => 78.50,
                'stock' => 13,
                'quantity' => 15,
            ],
            [
                'category_id' => 1,
                'name' => 'Exfoliating Facial Scrub',
                'description' => 'Gentle facial scrub with jojoba beads to remove dead skin and boost renewal',
                'image' => 'Exfoliating Facial Scrub.png',
                'price' => 42.99,
                'stock' => 18,
                'quantity' => 50,
            ],
            [
                'category_id' => 1,
                'name' => 'Under Eye Cream',
                'description' => 'Special under-eye cream with caffeine to reduce dark circles and puffiness',
                'image' => 'Under Eye Cream.png',
                'price' => 59.99,
                'stock' => 0,
                'quantity' => 43,
            ],
            [
                'category_id' => 1,
                'name' => 'Facial Toner',
                'description' => 'Gentle toner that restores skin balance and tightens pores after cleansing',
                'image' => 'Facial Toner.png',
                'price' => 28.50,
                'stock' => 13,
                'quantity' => 70,
            ],
            [
                'category_id' => 1,
                'name' => 'Moisturizing Sheet Mask',
                'description' => 'Sheet mask rich in moisturizing serum for instant hydration and results',
                'image' => 'Moisturizing Sheet Mask.png',
                'price' => 15.99,
                'stock' => 18,
                'quantity' => 19,
            ],
            [
                'category_id' => 1,
                'name' => 'vaseline',
                'description' => 'Pure Vaseline for moisturizing dry skin and lips, suitable for sensitive skin',
                'image' => 'vaseline.png',
                'price' => 12.99,
                'stock' => 8,
                'quantity' => 10,
            ],
            
            [
                'category_id' => 2, 
                'name' => 'Argan Oil Shampoo',
                'description' => 'Shampoo with argan oil to moisturize and strengthen dry and damaged hair.',
                'image' => 'Argan Oil Shampoo.png',
                'price' => 55.00,
                'stock' => 10,
                'quantity' => 30,
            ],
            [
                'category_id' => 2,
                'name' => 'Hair Serum',
                'description' => 'Hair serum to reduce frizz and add smoothness and shine.',
                'image' => 'Hair Serum.png',
                'price' => 65.99,
                'stock' => 8,
                'quantity' => 20,
            ],
            [
                'category_id' => 3,
                'name' => 'Lavender Body Wash',
                'description' => 'Relaxing body wash with lavender essential oil for a calming shower.',
                'image' => 'Lavender Body Wash.png',
                'price' => 32.50,
                'stock' => 8,
                'quantity' => 30,
            ],
            [
                'category_id' => 4,
                'name' => 'Baby Lotion',
                'description' => 'Soft, nourishing baby lotion for daily moisturizing after bath time.',
                'image' => 'Baby Lotion.png',
                'price' => 38.50,
                'stock' => 15,
                'quantity' => 40,
            ],
            [
                'category_id' => 4,
                'name' => 'Baby Powder',
                'description' => 'Talc-free baby powder to keep skin dry and prevent chafing.',
                'image' => 'Baby Powder.png',
                'price' => 29.99,
                'stock' => 12,
                'quantity' => 35,
            ],
            [
                'category_id' => 5,
                'name' => 'Arthritis Pain Relief Cream',
                'description' => 'Soothing cream for joint pain relief, specially formulated for seniors.',
                'image' => 'Arthritis Pain Relief Cream.png',
                'price' => 49.50,
                'stock' => 20,
                'quantity' => 30,
            ],
            [
                'category_id' => 6, 
                'name' => 'Sunscreen SPF 30+',
                'description' => 'Lightweight, non-greasy broad-spectrum sunscreen with SPF 50+ protection. Ideal for daily use and suitable for all skin types.',
                'image' => 'baby sunscreen.png',
                'price' => 55.00,
                'stock' => 11,
                'quantity' => 20,
            ],
            [
                'category_id' => 7,
                'name' => 'Foot Repair Cream',
                'description' => 'Intensive foot repair cream enriched with urea and shea butter to moisturize and soften dry, cracked heels.',
                'image' => 'foot_repair_cream.png',
                'price' => 38.50,
                'stock' => 8,
                'quantity' => 25,
            ],
            [
                'category_id' => 8, 
                'name' => 'Shower Sponge',
                'description' => 'Soft and durable shower sponge designed to provide a luxurious lather while gently exfoliating the skin.',
                'image' => 'Shower Sponge.png',
                'price' => 10.50,
                'stock' => 20,
                'quantity' => 150,
            ],
            [
                'category_id' => 8, 
                'name' => 'Exfoliating Body Scrub',
                'description' => 'Gentle exfoliating scrub that removes dead skin cells, leaving the skin smooth, rejuvenated, and glowing.',
                'image' => 'exfoliating_body_scrub.png',
                'price' => 32.00,
                'stock' => 13,
                'quantity' => 40,
            ],
            [
                'category_id' => 9, 
                'name' => 'Vitamin C 1000mg',
                'description' => 'High-potency Vitamin C supplement to support immune health, skin health, and antioxidant protection.',
                'image' => 'Vitamin C.png',
                'price' => 18.99,
                'stock' => 15,
                'quantity' => 70,
            ],
            [
                'category_id' =>9,
                'name' => 'Omega-3 Fish Oil',
                'description' => 'Omega-3 Fish Oil supplement rich in EPA and DHA to support heart health, joint health, and cognitive function.',
                'image' => 'Omega-3 Fish Oil.png',
                'price' => 22.50,
                'stock' => 12,
                'quantity' => 50,
            ],
            [
                'category_id' => 9, 
                'name' => 'Multivitamin Tablets',
                'description' => 'Daily multivitamin supplement providing essential vitamins and minerals to promote overall health and wellness.',
                'image' => 'Multivitamin Tablets.png',
                'price' => 29.99,
                'stock' => 18,
                'quantity' => 80,
            ],
            [
                'category_id' => 9,
                'name' => 'Probiotic Capsules',
                'description' => 'Probiotic supplement with beneficial bacteria to support digestive health and immune function.',
                'image' => 'Probiotic Capsules.png',
                'price' => 19.99,
                'stock' => 9,
                'quantity' => 40,
            ],
            [
                'category_id' => 10, 
                'name' => 'Adhesive Bandages',
                'description' => 'Flexible and sterile adhesive bandages for minor cuts, scrapes, and wounds.',
                'image' => 'Adhesive Bandages.png',
                'price' => 9.99,
                'stock' => 20,
                'quantity' => 50,
            ],
            [
                'category_id' => 10,
                'name' => 'Medical Gloves',
                'description' => 'Latex-free disposable gloves for hygienic handling of wounds and emergencies.',
                'image' => 'Medical Gloves.png',
                'price' => 14.00,
                'stock' => 18,
                'quantity' => 60,
            ],
            [
                'category_id' => 10,
                'name' => 'Sterile Gauze Pads',
                'description' => 'Soft, absorbent gauze pads for dressing wounds and absorbing fluids.',
                'image' => 'Sterile Gauze Pads.png',
                'price' => 8.99,
                'stock' => 13,
                'quantity' => 45,
            ],
            [
                'category_id' => 10,
                'name' => 'Medical Tape',
                'description' => 'Hypoallergenic medical adhesive tape to secure dressings and bandages.',
                'image' => 'Medical Tape.png',
                'price' => 4.50,
                'stock' => 12,
                'quantity' => 55,
            ],
            [
                'category_id' => 11, 
                'name' => 'Digital Thermometer',
                'description' => 'Fast and accurate digital thermometer for measuring body temperature.',
                'image' => 'Digital Thermometer.png',
                'price' => 59.99,
                'stock' => 12,
                'quantity' => 40,
            ],
            [
                'category_id' => 11,
                'name' => 'Blood Pressure Monitor',
                'description' => 'Automatic blood pressure monitor with large display and memory storage.',
                'image' => 'Blood Pressure Monitor.png',
                'price' => 199.00,
                'stock' => 8,
                'quantity' => 30,
            ],
            [
                'category_id' => 11,
                'name' => 'Digital Weight Scale',
                'description' => 'Smart digital scale for body weight measurement and health tracking.',
                'image' => 'Digital Weight Scale.png',
                'price' => 180.00,
                'stock' => 6,
                'quantity' => 15,
            ],
            [
                'category_id' => 12, 
                'name' => 'Paracetamol 500mg Tablets',
                'description' => 'Effective pain reliever and fever reducer for headaches, muscle aches, and colds.',
                'image' => 'Paracetamol.png',
                'price' => 22.00,
                'stock' => 30,
                'quantity' => 80,
            ],
            [
                'category_id' => 12,
                'name' => 'Cough Syrup (Adult)',
                'description' => 'Soothing syrup for relief from dry and productive cough in adults.',
                'image' => 'Cough Syrup.png',
                'price' => 35.00,
                'stock' => 12,
                'quantity' => 45,
            ],
            [
                'category_id' => 12,
                'name' => 'Antifungal Cream',
                'description' => 'Topical treatment for athlete’s foot, jock itch, and ringworm.',
                'image' => 'Antifungal Cream.png',
                'price' => 45.00,
                'stock' => 10,
                'quantity' => 30,
            ],
        ];

        foreach ($products as $product) {

            $sourcePath = public_path('images/products/' . $product['image']);
            $destinationPath = 'products/' . $product['image'];
            if (file_exists($sourcePath)) {
                Storage::disk('public')->put($destinationPath, File::get($sourcePath));
            }
            Product::create([
                'category_id' => $product['category_id'],
                'name' => $product['name'],
                'description' => $product['description'],
                'image' => $destinationPath,
                'price' => $product['price'],
                'stock' => $product['stock'],
                'quantity' => $product['quantity'] ,
            ]);
        }
    }
    
}
