<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\Category;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Storage;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'category_id' => 1,
                'name' => 'aloe vera gel',
                'description' => '99% natural aloe vera gel for moisturizing and soothing the skin, suitable for all skin types',
                'image' => 'aloe vera gel.png',
                'price' => 35.99,
                'stock' => 15,
                'quantity' => 55,
            ],
            [
                'category_id' => 1,
                'name' => 'Vitamin C Serum',
                'description' => '20% Vitamin C serum to brighten the skin, even tone, and reduce wrinkles',
                'image' => 'Vitamin C Serum.png',
                'price' => 89.99,
                'stock' => 15,
                'quantity' => 45,
            ],
            [
                'category_id' => 1,
                'name' => 'Foaming Facial Cleanser',
                'description' => 'Gentle foaming facial cleanser that deeply cleanses without drying the skin, soap-free',
                'image' => 'Foaming Facial Cleanser.png',
                'price' => 45.50,
                'stock' => 0,
                'quantity' => 60,
            ],
            [
                'category_id' => 1,
                'name' => 'Hydrating Facial Cream',
                'description' => 'Rich moisturizing cream with hyaluronic acid to keep skin hydrated for 24 hours',
                'image' => 'Hydrating Facial Cream.png',
                'price' => 65.00,
                'stock' => 9,
                'quantity' => 30,
            ],
            [
                'category_id' => 1,
                'name' => 'Micellar Water',
                'description' => 'Micellar water for gently removing makeup and cleansing the skin without rinsing',
                'image' => 'Micellar Water.png',
                'price' => 32.99,
                'stock' => 20,
                'quantity' => 100,
            ],
            [
                'category_id' => 1,
                'name' => 'Sunscreen SPF 50+',
                'description' => 'Lightweight, non-greasy broad-spectrum sunscreen for daily UV protection',
                'image' => 'Sunscreen.png',
                'price' => 55.00,
                'stock' => 11,
                'quantity' => 20,
            ],
            [
                'category_id' => 1,
                'name' => 'Night Repair Cream',
                'description' => 'Night cream rich in antioxidants to rejuvenate skin while sleeping',
                'image' => 'Night Repair Cream.png',
                'price' => 78.50,
                'stock' => 13,
                'quantity' => 15,
            ],
            [
                'category_id' => 1,
                'name' => 'Exfoliating Facial Scrub',
                'description' => 'Gentle facial scrub with jojoba beads to remove dead skin and boost renewal',
                'image' => 'Exfoliating Facial Scrub.png',
                'price' => 42.99,
                'stock' => 18,
                'quantity' => 50,
            ],
            [
                'category_id' => 1,
                'name' => 'Under Eye Cream',
                'description' => 'Special under-eye cream with caffeine to reduce dark circles and puffiness',
                'image' => 'Under Eye Cream.png',
                'price' => 59.99,
                'stock' => 0,
                'quantity' => 43,
            ],
            [
                'category_id' => 1,
                'name' => 'Facial Toner',
                'description' => 'Gentle toner that restores skin balance and tightens pores after cleansing',
                'image' => 'Facial Toner.png',
                'price' => 28.50,
                'stock' => 13,
                'quantity' => 70,
            ],
            [
                'category_id' => 1,
                'name' => 'Moisturizing Sheet Mask',
                'description' => 'Sheet mask rich in moisturizing serum for instant hydration and results',
                'image' => 'Moisturizing Sheet Mask.png',
                'price' => 15.99,
                'stock' => 18,
                'quantity' => 19,
            ],
            [
                'category_id' => 1,
                'name' => 'vaseline',
                'description' => 'Pure Vaseline for moisturizing dry skin and lips, suitable for sensitive skin',
                'image' => 'vaseline.png',
                'price' => 12.99,
                'stock' => 8,
                'quantity' => 10,
            ],
            
            [
                'category_id' => 2, 
                'name' => 'Argan Oil Shampoo',
                'description' => 'Shampoo with argan oil to moisturize and strengthen dry and damaged hair.',
                'image' => 'Argan Oil Shampoo.png',
                'price' => 55.00,
                'stock' => 10,
                'quantity' => 30,
            ],
            [
                'category_id' => 2,
                'name' => 'Hair Serum',
                'description' => 'Hair serum to reduce frizz and add smoothness and shine.',
                'image' => 'Hair Serum.png',
                'price' => 65.99,
                'stock' => 8,
                'quantity' => 20,
            ],
            [
                'category_id' => 3,
                'name' => 'Lavender Body Wash',
                'description' => 'Relaxing body wash with lavender essential oil for a calming shower.',
                'image' => 'Lavender Body Wash.png',
                'price' => 32.50,
                'stock' => 8,
                'quantity' => 30,
            ],
            [
                'category_id' => 4,
                'name' => 'Baby Lotion',
                'description' => 'Soft, nourishing baby lotion for daily moisturizing after bath time.',
                'image' => 'Baby Lotion.png',
                'price' => 38.50,
                'stock' => 15,
                'quantity' => 40,
            ],
            [
                'category_id' => 4,
                'name' => 'Baby Powder',
                'description' => 'Talc-free baby powder to keep skin dry and prevent chafing.',
                'image' => 'Baby Powder.png',
                'price' => 29.99,
                'stock' => 12,
                'quantity' => 35,
            ],
            [
                'category_id' => 5,
                'name' => 'Arthritis Pain Relief Cream',
                'description' => 'Soothing cream for joint pain relief, specially formulated for seniors.',
                'image' => 'Arthritis Pain Relief Cream.png',
                'price' => 49.50,
                'stock' => 20,
                'quantity' => 30,
            ],
            [
                'category_id' => 6, 
                'name' => 'Sunscreen SPF 30+',
                'description' => 'Lightweight, non-greasy broad-spectrum sunscreen with SPF 50+ protection. Ideal for daily use and suitable for all skin types.',
                'image' => 'baby sunscreen.png',
                'price' => 55.00,
                'stock' => 11,
                'quantity' => 20,
            ],
            [
                'category_id' => 7,
                'name' => 'Foot Repair Cream',
                'description' => 'Intensive foot repair cream enriched with urea and shea butter to moisturize and soften dry, cracked heels.',
                'image' => 'foot_repair_cream.png',
                'price' => 38.50,
                'stock' => 8,
                'quantity' => 25,
            ],
            [
                'category_id' => 8, 
                'name' => 'Shower Sponge',
                'description' => 'Soft and durable shower sponge designed to provide a luxurious lather while gently exfoliating the skin.',
                'image' => 'Shower Sponge.png',
                'price' => 10.50,
                'stock' => 20,
                'quantity' => 150,
            ],
            [
                'category_id' => 8, 
                'name' => 'Exfoliating Body Scrub',
                'description' => 'Gentle exfoliating scrub that removes dead skin cells, leaving the skin smooth, rejuvenated, and glowing.',
                'image' => 'exfoliating_body_scrub.png',
                'price' => 32.00,
                'stock' => 13,
                'quantity' => 40,
            ],
            [
                'category_id' => 9, 
                'name' => 'Vitamin C 1000mg',
                'description' => 'High-potency Vitamin C supplement to support immune health, skin health, and antioxidant protection.',
                'image' => 'Vitamin C.png',
                'price' => 18.99,
                'stock' => 15,
                'quantity' => 70,
            ],
            [
                'category_id' =>9,
                'name' => 'Omega-3 Fish Oil',
                'description' => 'Omega-3 Fish Oil supplement rich in EPA and DHA to support heart health, joint health, and cognitive function.',
                'image' => 'Omega-3 Fish Oil.png',
                'price' => 22.50,
                'stock' => 12,
                'quantity' => 50,
            ],
            [
                'category_id' => 9, 
                'name' => 'Multivitamin Tablets',
                'description' => 'Daily multivitamin supplement providing essential vitamins and minerals to promote overall health and wellness.',
                'image' => 'Multivitamin Tablets.png',
                'price' => 29.99,
                'stock' => 18,
                'quantity' => 80,
            ],
            [
                'category_id' => 9,
                'name' => 'Probiotic Capsules',
                'description' => 'Probiotic supplement with beneficial bacteria to support digestive health and immune function.',
                'image' => 'Probiotic Capsules.png',
                'price' => 19.99,
                'stock' => 9,
                'quantity' => 40,
            ],
            [
                'category_id' => 10, 
                'name' => 'Adhesive Bandages',
                'description' => 'Flexible and sterile adhesive bandages for minor cuts, scrapes, and wounds.',
                'image' => 'Adhesive Bandages.png',
                'price' => 9.99,
                'stock' => 20,
                'quantity' => 50,
            ],
            [
                'category_id' => 10,
                'name' => 'Medical Gloves',
                'description' => 'Latex-free disposable gloves for hygienic handling of wounds and emergencies.',
                'image' => 'Medical Gloves.png',
                'price' => 14.00,
                'stock' => 18,
                'quantity' => 60,
            ],
            [
                'category_id' => 10,
                'name' => 'Sterile Gauze Pads',
                'description' => 'Soft, absorbent gauze pads for dressing wounds and absorbing fluids.',
                'image' => 'Sterile Gauze Pads.png',
                'price' => 8.99,
                'stock' => 13,
                'quantity' => 45,
            ],
            [
                'category_id' => 10,
                'name' => 'Medical Tape',
                'description' => 'Hypoallergenic medical adhesive tape to secure dressings and bandages.',
                'image' => 'Medical Tape.png',
                'price' => 4.50,
                'stock' => 12,
                'quantity' => 55,
            ],
            [
                'category_id' => 11, 
                'name' => 'Digital Thermometer',
                'description' => 'Fast and accurate digital thermometer for measuring body temperature.',
                'image' => 'Digital Thermometer.png',
                'price' => 59.99,
                'stock' => 12,
                'quantity' => 40,
            ],
            [
                'category_id' => 11,
                'name' => 'Blood Pressure Monitor',
                'description' => 'Automatic blood pressure monitor with large display and memory storage.',
                'image' => 'Blood Pressure Monitor.png',
                'price' => 199.00,
                'stock' => 8,
                'quantity' => 30,
            ],
            [
                'category_id' => 11,
                'name' => 'Digital Weight Scale',
                'description' => 'Smart digital scale for body weight measurement and health tracking.',
                'image' => 'Digital Weight Scale.png',
                'price' => 180.00,
                'stock' => 6,
                'quantity' => 15,
            ],
            [
                'category_id' => 12, 
                'name' => 'Paracetamol 500mg Tablets',
                'description' => 'Effective pain reliever and fever reducer for headaches, muscle aches, and colds.',
                'image' => 'Paracetamol.png',
                'price' => 22.00,
                'stock' => 30,
                'quantity' => 80,
            ],
            [
                'category_id' => 12,
                'name' => 'Cough Syrup (Adult)',
                'description' => 'Soothing syrup for relief from dry and productive cough in adults.',
                'image' => 'Cough Syrup.png',
                'price' => 35.00,
                'stock' => 12,
                'quantity' => 45,
            ],
            [
                'category_id' => 12,
                'name' => 'Antifungal Cream',
                'description' => 'Topical treatment for athlete’s foot, jock itch, and ringworm.',
                'image' => 'Antifungal Cream.png',
                'price' => 45.00,
                'stock' => 10,
                'quantity' => 30,
            ],

            // vet products
            [
                'category_id' => 13,
                'name' => 'Dry Dog Food - Chicken Flavor',
                'description' => 'Complete and balanced dry dog food with real chicken for adult dogs',
                'image' => 'Dry Dog Food.png',
                'price' => 120.00,
                'stock' => 25,
                'quantity' => 100,
            ],
            [
                'category_id' => 13,
                'name' => 'Wet Cat Food - Tuna in Gravy',
                'description' => 'Canned wet cat food made with tender tuna in savory gravy',
                'image' => 'Cat Food.png',
                'price' => 15.50,
                'stock' => 50,
                'quantity' => 200,
            ],
            [
                'category_id' => 13,
                'name' => 'Puppy Starter Formula',
                'description' => 'Nutrient-rich puppy food to support growth and development in early months',
                'image' => 'Puppy Starter.png',
                'price' => 95.75,
                'stock' => 10,
                'quantity' => 80,
            ],
            [
                'category_id' => 13,
                'name' => 'Grain-Free Cat Food',
                'description' => 'High-protein grain-free dry food for cats with sensitive stomachs',
                'image' => 'Grain-Free Cat Food.png',
                'price' => 135.00,
                'stock' => 15,
                'quantity' => 60,
            ],
            [
                'category_id' => 13,
                'name' => 'Cat Treats - Salmon Bites',
                'description' => 'Soft and chewy salmon-flavored treats for cats',
                'image' => 'cat_salmon_bites.png',
                'price' => 20.00,
                'stock' => 40,
                'quantity' => 120,
            ],
            [
                'category_id' => 13,
                'name' => 'Puppy Starter Kit Food',
                'description' => 'Special formula for puppies with DHA for brain development.',
                'image' => 'Puppy Starter Kit Food.png',
                'price' => 45.00,
                'stock' => 18,
                'quantity' => 30,
            ],
            [
                'category_id' => 13,
                'name' => 'Grain-Free Dog Kibble',
                'description' => 'High-protein grain-free dry food with lamb and sweet potato.',
                'image' => 'Grain-Free Dog Kibble.png',
                'price' => 62.75,
                'stock' => 25,
                'quantity' => 50,
            ],
            [
                'category_id' => 14,
                'name' => 'Pet Shampoo - Oatmeal Formula',
                'description' => 'Gentle pet shampoo with oatmeal to soothe sensitive skin and leave fur soft',
                'image' => 'pet_shampoo_oatmeal.png',
                'price' => 60.00,
                'stock' => 20,
                'quantity' => 100,
            ],
            [
                'category_id' => 14,
                'name' => 'Flea & Tick Spray for Dogs and Cats',
                'description' => 'Fast-acting flea and tick spray with natural ingredients for pets',
                'image' => 'flea_tick_spray.png',
                'price' => 85.00,
                'stock' => 15,
                'quantity' => 80,
            ],
            [
                'category_id' => 14,
                'name' => 'Pet Nail Clippers',
                'description' => 'Stainless steel nail clippers for dogs and cats with non-slip grip',
                'image' => 'pet_nail_clippers.png',
                'price' => 35.00,
                'stock' => 30,
                'quantity' => 150,
            ],
            [
                'category_id' => 14,
                'name' => 'Pet Grooming Brush - Double Sided',
                'description' => 'Double-sided grooming brush for detangling and smoothing fur',
                'image' => 'pet_grooming_brush.png',
                'price' => 45.00,
                'stock' => 25,
                'quantity' => 120,
            ],
            [
                'category_id' => 14,
                'name' => 'Ear Cleaner for Pets',
                'description' => 'Mild and effective ear cleaning solution to remove wax and dirt',
                'image' => 'pet_ear_cleaner.png',
                'price' => 50.00,
                'stock' => 18,
                'quantity' => 90,
            ],
            [
                'category_id' => 14,
                'name' => 'Pet Cologne Spray',
                'description' => 'Refreshing and pet-safe cologne spray to keep your pet smelling fresh',
                'image' => 'pet_cologne_spray.png',
                'price' => 40.00,
                'stock' => 22,
                'quantity' => 110,
            ],
            [
                'category_id' => 15,
                'name' => 'Vitamin B Complex for Pets',
                'description' => 'B-complex supplement to support metabolism, nerves, and heart health.',
                'image' => 'Vitamin B Pets.png',
                'price' => 34.50,
                'stock' => 24,
                'quantity' => 48,
            ],
            [
                'category_id' => 15,
                'name' => 'Multivitamin Chews for Dogs',
                'description' => 'Daily multivitamin soft chews to support overall dog health and vitality',
                'image' => 'dog_multivitamin_chews.png',
                'price' => 95.00,
                'stock' => 25,
                'quantity' => 100,
            ],
            [
                'category_id' => 15,
                'name' => 'Omega-3 Fish Oil for Pets',
                'description' => 'Liquid omega-3 fish oil supplement for healthy skin and coat',
                'image' => 'omega3_pets.png',
                'price' => 120.00,
                'stock' => 18,
                'quantity' => 75,
            ],
            [
                'category_id' => 15,
                'name' => 'Calming Chews for Pets',
                'description' => 'Natural calming chews with chamomile and L-theanine for stress relief',
                'image' => 'calming_chews_pets.png',
                'price' => 105.00,
                'stock' => 16,
                'quantity' => 60,
            ],
            [
                'category_id' => 16,
                'name' => 'Interactive Ball Toy',
                'description' => 'Motion-activated ball that rolls and bounces to keep pets entertained',
                'image' => 'interactive_ball_toy.png',
                'price' => 70.00,
                'stock' => 20,
                'quantity' => 60,
            ],
            [
                'category_id' => 16,
                'name' => 'Chew Rope Toy for Dogs',
                'description' => 'Durable cotton rope toy for dogs, ideal for chewing and tug-of-war',
                'image' => 'chew_rope_dog_toy.png',
                'price' => 40.00,
                'stock' => 30,
                'quantity' => 100,
            ],
            [
                'category_id' => 16,
                'name' => 'Colorful Dog Toy',
                'description' => 'Small Dog toy filled with catnip for hours of feline fun',
                'image' => 'dog_toy.png',
                'price' => 20.00,
                'stock' => 35,
                'quantity' => 120,
            ],
            [
                'category_id' => 17,
                'name' => 'Pet Deodorizing Spray',
                'description' => 'A gentle deodorizing spray that keeps your pet smelling fresh between baths.',
                'image' => 'Pet Deodorizing Spray.png',
                'price' => 49.99,
                'stock' => 8,
                'quantity' => 10,
            ],
            [
                'category_id' => 17,
                'name' => 'Pet Tear Stain Remover',
                'description' => 'Safe formula to gently clean and prevent tear stains around your pet’s eyes.',
                'image' => 'Pet Tear Stain Remover.png',
                'price' => 27.99,
                'stock' => 6,
                'quantity' => 12,
            ],
            [
                'category_id' => 17,
                'name' => 'Pet Breath Freshener Spray',
                'description' => 'Easy-to-use mouth spray to reduce odor and maintain oral health in pets.',
                'image' => 'Pet Breath.png',
                'price' => 31.50,
                'stock' => 5,
                'quantity' => 6,
            ],
            [
                'category_id' => 18,
                'name' => 'Pet Wound Care Spray',
                'description' => 'Antiseptic spray to treat cuts, scrapes, and abrasions on pets, promotes faster healing.',
                'image' => 'Pet Wound Care Spray.png',
                'price' => 22.50,
                'stock' => 8,
                'quantity' => 8,
            ],
            [
                'category_id' => 18,
                'name' => 'Pet Bandage Wrap',
                'description' => 'Elastic bandage wrap to secure dressings or bandages on pets, providing support and protection.',
                'image' => 'Pet Bandage Wrap.png',
                'price' => 12.99,
                'stock' => 11,
                'quantity' => 12,
            ],
            [
                'category_id' => 18,
                'name' => 'Pet Stomach Soother',
                'description' => 'Natural remedy for pets with upset stomachs, helps reduce vomiting and diarrhea.',
                'image' => 'Pet Stomach Soother.png',
                'price' => 17.99,
                'stock' => 5,
                'quantity' => 7,
            ],
            [
                'category_id' => 18,
                'name' => 'Pet Medical Scissors',
                'description' => 'Durable scissors designed for cutting bandages, gauze, and other first aid materials on pets.',
                'image' => 'Pet Medical Scissors.png',
                'price' => 10.99,
                'stock' => 14,
                'quantity' => 18,
            ],
            [
                'category_id' => 18,
                'name' => 'Pet Thermometer',
                'description' => 'Accurate thermometer for measuring your pet’s body temperature for health monitoring.',
                'image' => 'Pet Thermometer.png',
                'price' => 19.50,
                'stock' => 10,
                'quantity' => 12,
            ],
            [
                'category_id' => 19,
                'name' => 'Flea & Tick Tablets',
                'description' => 'Oral medication for dogs and cats to eliminate and prevent fleas and ticks.',
                'image' => 'Flea Tick Tablets.png',
                'price' => 45.99,
                'stock' => 5,
                'quantity' => 10,
            ],
            [
                'category_id' => 19,
                'name' => 'Eye Drops for Pets',
                'description' => 'Sterile eye drops for treating irritation, infection, or allergies in pets’ eyes.',
                'image' => 'Eye Drops for Pets.png',
                'price' => 19.99,
                'stock' => 10,
                'quantity' => 12,
            ],
            [
                'category_id' => 19,
                'name' => 'Calming Aid for Pets',
                'description' => 'Natural calming medication to reduce stress and anxiety in pets during travel or storms.',
                'image' => 'Calming Aid for Pets.png',
                'price' => 27.45,
                'stock' => 12,
                'quantity' => 13,
            ],
            [
                'category_id' => 20,
                'name' => 'Pet Training Spray',
                'description' => 'Deterrent spray to keep pets away from unwanted areas while training.',
                'image' => 'Pet Wound Care Spray.png',
                'price' => 14.50,
                'stock' => 15,
                'quantity' => 20,
            ],
            [
                'category_id' => 20,
                'name' => 'Obedience Training Book',
                'description' => 'Step-by-step guide to basic and advanced dog training techniques.',
                'image' => 'Obedience Training Book.png',
                'price' => 22.00,
                'stock' => 4,
                'quantity' => 8,
            ],

        ];

        foreach ($products as $product) {

            $sourcePath = public_path('images/products/' . $product['image']);
            $destinationPath = 'products/' . $product['image'];
            if (file_exists($sourcePath)) {
                Storage::disk('public')->put($destinationPath, File::get($sourcePath));
            }
            Product::create([
                'category_id' => $product['category_id'],
                'name' => $product['name'],
                'description' => $product['description'],
                'image' => $destinationPath,
                'price' => $product['price'],
                'stock' => $product['stock'],
                'quantity' => $product['quantity'] ,
            ]);
        }
    }
    
}
